#database:
#  type: sqlite
#  database: ./example-data/database.sqlite3

uac:
  type: 'static'
  users:
    - user_id: 'abcdef'
      permissions:
        - manage_claims

auth:
  type: 'oidc'
  discovery_url: 'https://login-dev.vb3d.de/realms/VB3D-Dev/.well-known/openid-configuration'

database:
  username: dev
  password: '8HjDLSs73CYaSD4hDxdXyYz6T9MbrhsYkXB9aej28a3xHZS2h75ki2sWf6yc55p7'
  database: dev_bot-protection-server
  port: 5432
  ssl:
    rejectUnauthorized: false
  type: postgres
  host: 'db-01'
